version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: nestjs-postgres
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
    volumes:
      - ./scripts/pg-init.sql:/docker-entrypoint-initdb.d/pg-init.sql
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - api

volumes:
    postgres:

networks:
    api:
        driver: bridge